services:
  postgres:
    image: 'postgres:latest'
    platform: 'linux/arm64/v8'
    restart: always
    environment:
      - 'POSTGRES_DB=sbt-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
